In [4]:
import tensorflow as tf

In [6]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7])

In [7]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [10]:
for ele in dataset:
    print(ele)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [11]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [14]:
dataset2 = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])

In [15]:
dataset2

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [17]:
for ele2 in dataset2:
    print(ele2.numpy())

[1 2]
[3 4]
[5 6]


In [18]:
dataset_dic = tf.data.Dataset.from_tensor_slices({
    'a':[1,2,3,4],
    'b':[6,7,8,9],
    'c':[12,13,14,15]
})

In [19]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [22]:
for ele_dic in dataset_dic:
    print(ele_dic)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=15>}


In [23]:
import numpy as np

In [25]:
dataset_np = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [26]:
for ele_np in dataset_np:
    print(ele_np)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [27]:
for ele_np in dataset_np.take(4): # 取出前四个
    print(ele_np)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [29]:
next(iter(dataset_np.take(1)))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [30]:
dataset_np = dataset_np.shuffle(7) #乱序

In [34]:
for ele_np in dataset_np:
    print(ele_np)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [35]:
dataset_np = dataset_np.shuffle(7)
dataset_np = dataset_np.repeat(count = 3) #重复3次，为None无限循环

In [36]:
for ele_np in dataset_np:
    print(ele_np)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [37]:
dataset_np = dataset_np.shuffle(7)
dataset_np = dataset_np.repeat(count = 3)
dataset_np = dataset_np.batch(3) #每次请求3个

In [38]:
for ele_np in dataset_np:
    print(ele_np)

tf.Tensor([2 5 7], shape=(3,), dtype=int32)
tf.Tensor([1 5 2], shape=(3,), dtype=int32)
tf.Tensor([3 6 1], shape=(3,), dtype=int32)
tf.Tensor([5 4 6], shape=(3,), dtype=int32)
tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([3 1 7], shape=(3,), dtype=int32)
tf.Tensor([6 4 7], shape=(3,), dtype=int32)
tf.Tensor([2 5 1], shape=(3,), dtype=int32)
tf.Tensor([6 3 4], shape=(3,), dtype=int32)
tf.Tensor([5 7 3], shape=(3,), dtype=int32)
tf.Tensor([2 6 3], shape=(3,), dtype=int32)
tf.Tensor([6 2 7], shape=(3,), dtype=int32)
tf.Tensor([1 5 4], shape=(3,), dtype=int32)
tf.Tensor([4 7 1], shape=(3,), dtype=int32)
tf.Tensor([6 1 4], shape=(3,), dtype=int32)
tf.Tensor([3 7 3], shape=(3,), dtype=int32)
tf.Tensor([2 7 4], shape=(3,), dtype=int32)
tf.Tensor([6 2 2], shape=(3,), dtype=int32)
tf.Tensor([3 6 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 5], shape=(3,), dtype=int32)
tf.Tensor([5 7 5], shape=(3,), dtype=int32)


In [39]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [40]:
dataset = dataset.map(tf.square) # 取平方

In [41]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
